---
# tasks file for role-zabbix-agent

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Baixando o repositorio do zabiix
  command: wget https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb

- name: Referenciando o repositorio do zabiix
  ansible.builtin.command:
    cmd: "/usr/bin/sudo dpkg -i zabbix-release_6.4-1+debian11_all.deb"
    chdir: "/home/brd"

- name: instalando pacotes do zabbix-agent
  apt:
    name:
    - zabbix-agent

- name: iniciando o zabbix agent
  service:
    name: zabbix-agent
    enabled: yes
    state: restarted

- name: Configurando ServerActive no arquivo zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive='
    line: 'ServerActive=172.30.0.60'

- name: Configurando Hostname no arquivo zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^# Hostname='
    line: 'Hostname={{ ansible_hostname }}'
